import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserSession from "@/components/UserSession";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="bg-gradient-to-br from-gray-950 to-gray-900 min-h-screen font-sans">
        <nav className="w-full sticky top-0 z-50 bg-gray-950/90 border-b border-neon-green/30 shadow flex items-center justify-between px-6 py-3">
          <a href="/" className="text-neon-green font-extrabold text-xl tracking-wide drop-shadow hover:underline">Gamefolio</a>
          <div className="flex gap-4 items-center">
            <UserSession />
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
